# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 878c5babf19240e2378a9e484d966246fc1a9364be3ea02562189ea62860a6578df0c4e6104cc561db50e4fb0a696a34d89ef81a9a9c55d096b5913cc02f2f22

test:
  secret_key_base: 4c39daab60456844d61eebd152777d1cf94ebd0759d7fb02ae03857bf72c0e48f1105ea4384828b670c3286594cef684dbaede711ae8e0b2336e1bbcdb315068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
